[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FederatedLearning2026"
version = "0.0.1"
#versions below mostly based on what I have installed on my system
requires-python = "==3.13.14" #tenseal does not work with python 3.14
dependencies = [
    "flwr[simulation]>=1.28.0",
    "flwr-datasets[vision]>=0.6.0",
    "torch>=2.8.0",
    "torchvision==0.23.0",
    "opacus>=1.6.0",
    "numpy>=2.4.6",
    "scikit-learn>=1.9.0",
    "tenseal>=0.3.16",
    "scipy>=1.17.1"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "Fahran Bajaj"
flwr-version-target = "1.31.0"

[tool.flwr.app.components]
serverapp = "src.server_app:app"
clientapp = "src.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 10
fraction-evaluate = 1
fraction-malicious = 0
local-epochs = 1
learning-rate = 0.1
batch-size = 2
trusted-parties = 2
save-model = false
noise-multiplier = 0.1
max-norm = 1
reproducible = false