[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project]
name = "FederatedLearning2026"
version = "0.0.1"
requires-python = "==3.13.14"
dependencies = [ "datasets<4.0.0", "flwr[simulation]>=1.28.0", "flwr-datasets[vision]>=0.6.0", "torchvision==0.23.0", "torch>=2.8.0", "opacus>=1.6.0", "numpy>=2.4.6", "scikit-learn>=1.9.0", "tenseal>=0.3.16", "scipy>=1.17.1", "dp-accounting>=0.6.0", "pandas>=3.0.3",]

[tool.flwr.app]
publisher = "Fahran Bajaj"
flwr-version-target = "1.31.0"

[tool.flwr.app.components]
serverapp = "src.server_app:app"
clientapp = "src.client_app:app"

[tool.flwr.app.config]
dataset = "EMNIST"
attack-type = ""
adaptive-attack-lambda = 0.5
lit-attack-alpha = 0.2
use-dp = true
noise-reduction = true
concentration-parameter = 5
max-num-server-rounds = 500
fraction-evaluate = 0
fraction-malicious = 0.0
local-epochs = 1
learning-rate = 0.03
batch-size = 128
trusted-fraction = 0.5
save-model = false
epsilon = 1
delta = 1e-5
max-norm = 10
write-results = false
write-time = false
measure-messages = true
evaluate-train = false
results-directory = "results"
num-model-updates = 100

[tool.hatch.build.targets.wheel]
packages = [ ".",]
