[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "FederatedLearning2026"
version = "0.0.1"
requires-python = "==3.13.14"
#versions below mostly based on what I have installed on my system
dependencies = [
    "flwr[simulation]>=1.28.0",
    "flwr-datasets[vision]>=0.6.0",
    "torchvision==0.23.0",
    "torch>=2.8.0",
    "opacus>=1.6.0",
    "numpy>=2.4.6",
    "scikit-learn>=1.9.0",
    "tenseal>=0.3.16",
    "scipy>=1.17.1",
    "dp-accounting>=0.6.0"
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "Fahran Bajaj"
flwr-version-target = "1.31.0"

[tool.flwr.app.components]
serverapp = "src.server_app:app"
clientapp = "src.client_app:app"

[tool.flwr.app.config]
max-num-server-rounds = 30
fraction-evaluate = 0
fraction-malicious = 0
local-epochs = 1
learning-rate = 0.01
batch-size = 32
trusted-fraction = 0.5
save-model = false
epsilon = 1
delta = 0.00001
max-norm = 1
reproducible = false
write-results = false
results-directory = "results"
num-model-updates = -1 #negative to run for until process ends from max-num-server-rounds